learning numpy

In [38]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [39]:
import numpy as np

In [40]:
print("1d array")
a = np.array([1,2,3,4,5])
print(a)


print("2d array")
b = np.array([[1,2,3,4,5],
              [1,2,3,4,5,]])
print(b)


print("3d array")
c = np.array([[[1,2,3,4,5],
               [1,2.5,3,4,6],
               [2,3,4,56,7]]])
print(c)


type(a)




1d array
[1 2 3 4 5]
2d array
[[1 2 3 4 5]
 [1 2 3 4 5]]
3d array
[[[ 1.   2.   3.   4.   5. ]
  [ 1.   2.5  3.   4.   6. ]
  [ 2.   3.   4.  56.   7. ]]]


numpy.ndarray

In [41]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [42]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [47]:
c.transpose()

array([[[ 1. ],
        [ 1. ],
        [ 2. ]],

       [[ 2. ],
        [ 2.5],
        [ 3. ]],

       [[ 3. ],
        [ 3. ],
        [ 4. ]],

       [[ 4. ],
        [ 4. ],
        [56. ]],

       [[ 5. ],
        [ 6. ],
        [ 7. ]]])

In [44]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
float64
